<?php

namespace Moment;

use Moment\Moment;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-01 at 20:26:58.
 */
class MomentHelperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers MomentHelper methods
     */
    public function testMomentHelper()
    {

        $data = '-0100';
        $offset = MomentHelper::getTimeZoneOffset($data);
        $this->assertEquals(-3600, $offset);

        $data = '+00:00';
        $offset = MomentHelper::getTimeZoneOffset($data);
        $this->assertEquals(0, $offset);

        $data = '+0600';
        $offset = MomentHelper::getTimeZoneOffset($data);
        $this->assertEquals(21600, $offset);

        $data = '+19800';
        $offset = MomentHelper::getTimeZoneName($data);
        $this->assertEquals('Asia/Kolkata', $offset);

        $data = '0';
        $offset = MomentHelper::getTimeZoneName($data);
        $this->assertEquals('Europe/London', $offset);

        $data = '-28800';
        $offset = MomentHelper::getTimeZoneName($data);
        $this->assertEquals('America/Los_Angeles', $offset);

    }

}
