<?php

namespace Moment;

use Moment\Moment;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-01 at 20:26:58.
 */
class MomentHelperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers MomentHelper methods
     */
    public function testMomentHelper()
    {
        $data = '1923-12-31 12:30:00';
        $tz = MomentHelper::getTimeZoneFromDate($data);
        $this->assertEquals('+00:00', $tz);

        $data = '2014-11-02T05:12:15+07:00';
        $tz = MomentHelper::getTimeZoneFromDate($data);
        $this->assertEquals('+07:00', $tz);

        $data = '2014-11-02T05:12:15-01:00';
        $tz = MomentHelper::getTimeZoneFromDate($data);
        $this->assertEquals('-01:00', $tz);
        
        $data = '2014-11-02T05:12:15-01:00';
        $isiso8601 = MomentHelper::isValidISO8601Date($data);
        $this->assertTrue($isiso8601);

        $data = '2014-11-02T05:12:15+0530';
        $isiso8601 = MomentHelper::isValidISO8601Date($data);
        $this->assertTrue($isiso8601);

        $data = '12th Jan 2014';
        $isiso8601 = MomentHelper::isValidISO8601Date($data);
        $this->assertFalse($isiso8601);

        $data = '-0100';
        $offset = MomentHelper::getTimeZoneOffset($data);
        $this->assertEquals(-3600, $offset);

        $data = '+0600';
        $offset = MomentHelper::getTimeZoneOffset($data);
        $this->assertEquals(21600, $offset);

        $data = '+19800';
        $offset = MomentHelper::getTimeZoneName($data);
        $this->assertEquals('Asia/Kolkata', $offset);

        $data = '0';
        $offset = MomentHelper::getTimeZoneName($data);
        $this->assertEquals('Europe/London', $offset);

        $data = '-28800';
        $offset = MomentHelper::getTimeZoneName($data);
        $this->assertEquals('America/Los_Angeles', $offset);

    }

}
