name: "Integrate"

on:
  pull_request: null
  push:
    branches:
      - "master"

jobs:
  tests:
    name: "Tests"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}'"

      - name: "Validate composer.json and composer.lock"
        run: "composer validate"

      - name: "Install dependencies"
        run: "composer install --prefer-dist --no-progress --no-suggest"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit -c tests/build.xml"
